
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456a!
    username: root
    url: jdbc:mysql://127.0.1:13306/sch_list?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    druid:
      test-on-borrow: true
      test-while-idle: true
      initialSize: 5
      minIdle: 10
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
sch:
  list:
    definition-builder-clazz: com.sch.list.definition.DbListDefinitionBuilder
server:
  port: 1912
